categories:

  - title: 'New features'
    labels:
      - 'enhancement'

  - title: 'Bug Fixes'
    labels:
      - 'bug'

  - title: 'Maintenance'
    label:
      - 'code quality'
      - 'documentation'

  - title: 'Dependency updates'
    label:
      -  'dependencies'

change-template: '- $TITLE #$NUMBER'

sort-direction: 'ascending'

template: |
  # What's Changed

  $CHANGES

  # Thanks
  Many thanks for collaboration on this release for: $CONTRIBUTORS
