name: Auto approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:

      - uses: alexwilson/enable-github-automerge-action@1.0.0
        if: >
          github.actor == 'dependabot[bot]'
          || github.actor == 'dependabot-preview[bot]'
        with:
          merge-method: "REBASE"
          github-token: "${{ secrets.TECH_TOKEN }}"

      - uses: hmarr/auto-approve-action@v2.1.0
        if: >
          github.actor == 'dependabot[bot]'
          || github.actor == 'dependabot-preview[bot]'
          || github.actor == 'slawekjaranowski'
        with:
          github-token: "${{ secrets.TECH_TOKEN }}"
