name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

  schedule:
    - cron: '55 5 * * 5'

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest

    if: |
      startsWith(github.ref, 'refs/tags/')
      || !startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare release')

    outputs:
      branch: ${{ steps.setup.outputs.branch }}
      date-ym: ${{ steps.setup.outputs.date-ym }}

    steps:
      - id: setup
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          echo "::set-output name=date-ym::$(date +%y%m)"

  verify:
    name: Build ${{ matrix.os }} jdk${{ matrix.java }}
    needs: setup

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        java: [ 8, 11, 16 ]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            ~/.sonar/cache
          key: ${{ needs.setup.outputs.date-ym}}-${{ matrix.os }}-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ needs.setup.outputs.date-ym}}-${{ matrix.os }}-jdk${{ matrix.java }}-

      - uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          sonatypeSnapshots: true
          properties: |
            [
              {"sonar.login": "2de0e32b2b3108965f76a4713ba2028978c233ed"},
              {"sonar.branch.name": "${{ needs.setup.outputs.branch }}"}
            ]

      - name: sonar setup
        id: sonar
        run: echo "::set-output name=mvn-args::sonar:sonar -P coverage"
        if: >
          matrix.os == 'ubuntu-latest'
          && matrix.java == '11'
          && github.repository_owner == 's4u'
          && startsWith( github.ref, 'refs/heads/')

      - run: mvn --errors --show-version verify ${{steps.sonar.outputs.mvn-args}}
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}

  site-test:
    name: Maven Site - Test
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ needs.setup.outputs.date-ym}}-maven-site-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ needs.setup.outputs.date-ym}}-maven-site-test-

      - uses: actions/setup-java@v2.1.0
        with:
          java-version: 8
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          sonatypeSnapshots: true

      - run: mvn --errors --show-version site

  deploy:
    name: Build - Deploy
    concurrency: maven-deploy

    if: github.repository_owner == 's4u'

    needs: [ setup, verify, site-test ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ needs.setup.outputs.date-ym}}-ubuntu-latest-jdk8-deploy-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ needs.setup.outputs.date-ym}}-ubuntu-latest-jdk8-

      - uses: actions/setup-java@v2.1.0
        with:
          java-version: 8
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          sonatypeSnapshots: true
          servers: '[{"id": "ossrh", "username": "${env.OSS_USER}", "password": "${env.OSS_PASS}"}]'

      - run: mvn --errors --show-version deploy -Dmaven.test.skip=true
        env:
          OSS_USER: ${{ secrets.OSS_USER }}
          OSS_PASS: ${{ secrets.OSS_PASS }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}

  site-deploy:
    name: Site - Deploy
    concurrency: site-deploy
    if: github.repository_owner == 's4u' && startsWith(github.ref, 'refs/tags/')

    needs: [ setup, deploy ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ needs.setup.outputs.date-ym}}-maven-site-deploy-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ needs.setup.outputs.date-ym}}-maven-site-

      - uses: actions/setup-java@v2.1.0
        with:
          java-version: 8
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          sonatypeSnapshots: true
          properties: |
            [
              {"username": "git"},
              {"password": "${{ secrets.TECH_TOKEN }}"},
              {"scmpublish.pubScmUrl": "scm:git:${{ github.event.repository.url}}"},
              {"scmpublish.dryRun": "false"}
            ]

      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Action"

      - run: mvn --errors --show-version site-deploy

  publish-release:
    name: Publish Release
    concurrency: release-drafter

    if: github.repository_owner == 's4u' && startsWith(github.ref, 'refs/tags/')

    needs: site-deploy
    runs-on: ubuntu-latest

    steps:
      - id: tag
        run: echo "::set-output name=name::${GITHUB_REF#refs/tags/}"

      - uses: release-drafter/release-drafter@v5.15.0
        with:
          publish: false
          name: ${{ steps.tag.outputs.name }}
          tag: ${{ steps.tag.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
