name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

  schedule:
    - cron: '55 5 * * 5'

jobs:

  verify:
    name: Build ${{ matrix.os }} jdk${{ matrix.java }}
    if: |
      startsWith(github.ref, 'refs/tags/')
      || !startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare release')

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        java: [ 8, 11, 15 ]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.m2/repository
            ~/.sonar/cache
          key: ${{ matrix.os }}-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.os }}-jdk${{ matrix.java }}-

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java }}

      - uses: s4u/maven-settings-action@v2.3.0
        with:
          sonatypeSnapshots: true

      - run: mvn verify
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}


      - run: mvn sonar:sonar -Dsonar.branch.name=${GITHUB_REF#refs/heads/} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        if: >
          matrix.os == 'ubuntu-latest'
          && matrix.java == '11'
          && github.repository_owner == 's4u'
          && startsWith( github.ref, 'refs/heads/')

  site-test:
    name: Maven Site - Test
    if: |
      startsWith(github.ref, 'refs/tags/')
      || !startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare release')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: maven-site-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-site-test-

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          sonatypeSnapshots: true

      - run: mvn --no-transfer-progress site

  deploy:
    name: Build Deploy ubuntu-latest jdk8
    if: >
      github.repository_owner == 's4u'
      && (
        startsWith(github.ref, 'refs/tags/')
        || !startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare release')
      )

    needs: [ verify, site-test ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: deploy-ubuntu-latest-jdk8-${{ hashFiles('**/pom.xml') }}
          restore-keys: deploy-ubuntu-latest-jdk8-

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - uses: s4u/maven-settings-action@v2.3.0
        with:
          sonatypeSnapshots: true
          servers: '[{"id": "ossrh", "username": "${env.OSS_USER}", "password": "${env.OSS_PASS}"}]'

      - run: mvn deploy -Dmaven.test.skip=true
        env:
          OSS_USER: ${{ secrets.OSS_USER }}
          OSS_PASS: ${{ secrets.OSS_PASS }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}

  site-deploy:
    name: Maven Site - Deploy
    if: github.repository_owner == 's4u' && startsWith(github.ref, 'refs/tags/')

    needs: deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: maven-site-deploy-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-site-deploy-

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - uses: s4u/maven-settings-action@v2.3.0
        with:
          sonatypeSnapshots: true
          properties: |
            [
              {"username": "git"},
              {"password": "${{ secrets.TECH_TOKEN }}"},
              {"scmpublish.pubScmUrl": "scm:git:${{ github.event.repository.url}}"},
              {"scmpublish.dryRun": "false"}
            ]

      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Action"

      - run: mvn --no-transfer-progress site-deploy

  publish-release:
    name: Publish Release
    if: github.repository_owner == 's4u' && startsWith(github.ref, 'refs/tags/')

    needs: site-deploy
    runs-on: ubuntu-latest

    steps:
      - id: tag
        run: echo "::set-output name=name::${GITHUB_REF#refs/tags/}"

      - uses: release-drafter/release-drafter@v5.13.0
        with:
          publish: true
          name: ${{ steps.tag.outputs.name }}
          tag: ${{ steps.tag.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
