name: Pull requests

on:
  pull_request:
    branches:
      - 'master'

jobs:

  verify:
    name: Verify ${{ matrix.os }} jdk${{ matrix.java }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        java: [ 8, 11, 15 ]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.m2/repository
            ~/.sonar/cache
          key: ${{ matrix.os }}-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.os }}-jdk${{ matrix.java }}-

      - uses: actions/setup-java@v2.0.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          sonatypeSnapshots: true

      - run: mvn --errors --show-version verify

      - run: mvn --errors --show-version sonar:sonar
        if: >
          matrix.os == 'ubuntu-latest'
          && matrix.java == '11'
          && github.repository_owner == 's4u'
        env:
          SONARQUBE_SCANNER_PARAMS: >
            {
              "sonar.pullrequest.key": "${{ github.event.number }}",
              "sonar.pullrequest.base": "${{ github.event.pull_request.base.ref }}",
              "sonar.pullrequest.branch": "${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}",
              "sonar.pullrequest.github.repository": "${{ github.repository }}",
              "sonar.login": "2de0e32b2b3108965f76a4713ba2028978c233ed",
              "sonar.scm.revision": "${{ github.event.pull_request.head.sha }}"
            }

  site-test:
    name: Maven Site - Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: maven-site-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-site-test-

      - uses: actions/setup-java@v2.0.0
        with:
          java-version: 8
          distribution: 'adopt'

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          sonatypeSnapshots: true

      - run: mvn --errors --show-version site
