name: Pull requests

on:
  pull_request:
    branches:
      - 'master'
      - 'main'

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest

    outputs:
      date-ym: ${{ steps.setup.outputs.date-ym }}

    steps:
      - id: setup
        run: echo "::set-output name=date-ym::$(date +%y%m)"

  verify:
    name: Verify ${{ matrix.os }} jdk${{ matrix.java }}
    needs: setup

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        java: [ 8, 11, 16, 17-ea ]

    steps:
      - uses: s4u/setup-maven-action@v1.2.0
        with:
          checkout-fetch-depth: 0
          java-version: ${{ matrix.java }}
          settings-sonatypeSnapshots: true
          settings-properties: |
            [
              {"sonar.pullrequest.key": "${{ github.event.number }}"},
              {"sonar.pullrequest.base": "${{ github.event.pull_request.base.ref }}"},
              {"sonar.pullrequest.branch": "${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}"},
              {"sonar.pullrequest.github.repository": "${{ github.repository }}"},
              {"sonar.login": "2de0e32b2b3108965f76a4713ba2028978c233ed"},
              {"sonar.scm.revision": "${{ github.event.pull_request.head.sha }}"}
            ]
          cache-prefix: ${{ needs.setup.outputs.date-ym}}-
          cache-path-add: ~/.sonar/cache

      - name: sonar setup
        id: sonar
        run: echo "::set-output name=mvn-args::sonar:sonar -P coverage"
        if: >
          matrix.os == 'ubuntu-latest'
          && matrix.java == '11'
          && github.repository_owner == 's4u'

      - run: mvn --errors --show-version verify ${{steps.sonar.outputs.mvn-args}}

  site-test:
    name: Maven Site - Test
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - uses: s4u/setup-maven-action@v1.2.0
        with:
          java-version: 8
          settings-sonatypeSnapshots: true
          cache-prefix: ${{ needs.setup.outputs.date-ym}}-maven-site-

      - run: mvn --errors --show-version site
