name: Release Drafter

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 's4u'
      && (startsWith(github.ref, 'refs/tags/') || !startsWith(github.event.head_commit.message , '[maven-release-plugin]'))

    steps:
      - id: is-tag
        run: |
          echo "::set-output name=name::${GITHUB_REF#refs/tags/}"
          echo "::set-output name=tag::true"
        if: github.repository_owner == 's4u' && startsWith(github.ref, 'refs/tags/')

      - uses: release-drafter/release-drafter@v5.13.0
        with:
          publish: ${{ steps.is-tag.outputs.tag }}
          name: ${{ steps.is-tag.outputs.name }}
          tag: ${{ steps.is-tag.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
