name: Release Drafter

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    concurrency: release-drafter

    steps:
      - uses: s4u/.github/.github/workflows/auto-approve.yml@master
