name: verify linux,win,mac - jdk 8,11,13

on:
  push:
    branches:
      - 'master'
    tags:

  pull_request:
    branches:
      - 'master'
    tags:

  schedule:
    - cron: '22 22 */16 * *'


jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [8, 11, 13]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-jdk${{ matrix.java }}
    if: startsWith( github.event.head_commit.message , '[maven-release-plugin] prepare release') != true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key:          verify-${{ matrix.os }}-jdk${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: verify-${{ matrix.os }}-jdk${{ matrix.java }}-maven-


      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: s4u/maven-settings-action@v2
        with:
          sonatypeSnapshots: true

      - run: mvn clean verify
